### ISSUE TITLE
Error getting video 

### ISSUE THREAD

**Issue by dishapatel010** [sjdiego/reels-tg-bot#4]
i have deployed this web app on heroku with all perfect env vars but still bot is throwing error for reels url.

![Untitled](https://user-images.githubusercontent.com/71930916/115340099-bc03ea80-a1c3-11eb-9b19-338bfd87a1c1.png)

after trying some minutes still same error!! Help me / tell a way to make app run well

**Comment by sjdiego** [comment]
Sounds that this could be related to #1

I can suggest you to run the app from local server, or finding a way to reach Instagram servers with an IP address that is not flagged as proxy/hosting.

**Comment by dishapatel010** [comment]
i will seen in future XD!!
